dzuelke_symfony_con2014_raffle:
    resource: "@DzuelkeSymfonyCon2014RaffleBundle/Controller/"
    type:     annotation
    prefix:   /

_home:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: dzuelke_symfonycon2014_raffle_default_raffles
